version: "3"
services:
  opensearch:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch
    ports:
      - 9200:9200
    environment:
      - "DISABLE_SECURITY_PLUGIN=true"
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
volumes:
  data: