version: "3"
services:
  sonar:
    image: sonarqube
    container_name: sonar
    ports:
      - 9000:9000
      - 9002:9002
    volumes:
      - sonar_data:/opt/sonarqube/data
volumes:
 sonar_data:
