version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTIC_PASSWORD=change_me
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - path.logs=/var/log/
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        - "CMD-SHELL"
        - "curl -s -I http://localhost:9200/_cluster/health || exit 1"
      interval: 10s
      timeout: 10s
      retries: 120

  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=change_me
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        until curl -s -X POST  -u "elastic:change_me" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"change_me\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_APM_ACTIVE=true
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=change_me
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.5.1
    container_name: apm-server
    ports:
      - 8200:8200
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E apm-server.kibana.protocol=http
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
        -E apm-server.kibana.username=elastic
        -E apm-server.kibana.password=change_me
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=change_me

volumes:
  elasticsearch_data:
  certs:
    driver: local
