
version: '3'

services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    volumes:
      - data:/var/lib/postgresql/data
  kong-migrations:
    image: "kong:2.1.4-alpine"
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    networks:
      - kong-net

  kong:
    image: "kong:2.1.4-alpine"
    user: "root"
    restart: on-failure
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"

  konga:
    container_name: konga
    image: pantsel/konga:latest
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_DATABASE: postgres
      DB_HOST: db
      DB_PASSWORD: kong
      DB_USER: kong
      NODE_ENV: development
      TOKEN_SECRET: ahfdjgjgf79JKLFHJKh978953kgdfjkl
    depends_on:
      - db
    ports:
      - "1337:1337"

volumes:
  data:
networks:
  kong-net:
    driver: bridge